### ISSUE TITLE
Remove old (20 minutes or more) messages from chat

### ISSUE THREAD

**Issue by XanthosX** [XanthosX/vintel#15]
This will help keep things from getting slow.

**Comment by chriz3W** [comment]
Oh dear … I will have to acctually work now ☺

/chriz


Från: XanthosX [mailto:notifications@github.com]
Skickat: den 4 januari 2016 00:18
Till: XanthosX/vintel <vintel@noreply.github.com>
Kopia: chriz3W <cberg@3wsolutions.se>
Ämne: Re: [vintel] Remove old (20 minutes or more) messages from chat (#15)


Assigned #15<https://github.com/XanthosX/vintel/issues/15> to @chriz3W<https://github.com/chriz3W>.
